// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountSettings struct {
	LangID               uint64   `protobuf:"varint,1,opt,name=LangID,proto3" json:"LangID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountSettings) Reset()         { *m = AccountSettings{} }
func (m *AccountSettings) String() string { return proto.CompactTextString(m) }
func (*AccountSettings) ProtoMessage()    {}
func (*AccountSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{0}
}

func (m *AccountSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSettings.Unmarshal(m, b)
}
func (m *AccountSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSettings.Marshal(b, m, deterministic)
}
func (m *AccountSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSettings.Merge(m, src)
}
func (m *AccountSettings) XXX_Size() int {
	return xxx_messageInfo_AccountSettings.Size(m)
}
func (m *AccountSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSettings.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSettings proto.InternalMessageInfo

func (m *AccountSettings) GetLangID() uint64 {
	if m != nil {
		return m.LangID
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountSettings)(nil), "account.AccountSettings")
}

func init() {
	proto.RegisterFile("account/account.proto", fileDescriptor_d66906c5773c9d08)
}

var fileDescriptor_d66906c5773c9d08 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x92, 0x26, 0x17, 0xbf, 0x23, 0x84, 0x19, 0x9c, 0x5a, 0x52, 0x92, 0x99, 0x97, 0x5e, 0x2c, 0x24,
	0xc6, 0xc5, 0xe6, 0x93, 0x98, 0x97, 0xee, 0xe9, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x12, 0x04,
	0xe5, 0x39, 0x19, 0x46, 0xe9, 0xa7, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea,
	0x57, 0x26, 0x16, 0x95, 0x56, 0xe9, 0x27, 0x16, 0x14, 0xe8, 0x67, 0xe6, 0x95, 0xa4, 0x16, 0xe5,
	0x25, 0xe6, 0x80, 0x39, 0x60, 0xe3, 0x61, 0x96, 0x25, 0xb1, 0x81, 0xb9, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x88, 0x5c, 0xcc, 0xfd, 0x86, 0x00, 0x00, 0x00,
}
