// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Session struct {
	User                 *User            `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	AccountSettings      *AccountSettings `protobuf:"bytes,2,opt,name=AccountSettings,proto3" json:"AccountSettings,omitempty"`
	SnAccounts           []*SnAccount     `protobuf:"bytes,3,rep,name=SnAccounts,proto3" json:"SnAccounts,omitempty"`
	JwtClaims            *JwtClaims       `protobuf:"bytes,4,opt,name=JwtClaims,proto3" json:"JwtClaims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Session) GetAccountSettings() *AccountSettings {
	if m != nil {
		return m.AccountSettings
	}
	return nil
}

func (m *Session) GetSnAccounts() []*SnAccount {
	if m != nil {
		return m.SnAccounts
	}
	return nil
}

func (m *Session) GetJwtClaims() *JwtClaims {
	if m != nil {
		return m.JwtClaims
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "proto.Session")
}

func init() {
	proto.RegisterFile("session.proto", fileDescriptor_3a6be1b361fa6f14)
}

var fileDescriptor_3a6be1b361fa6f14 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2e,
	0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x5c, 0xa5,
	0xc5, 0xa9, 0x45, 0x10, 0x21, 0x29, 0x81, 0xe2, 0xbc, 0xf8, 0xc4, 0xe4, 0xe4, 0xfc, 0xd2, 0xbc,
	0x12, 0xa8, 0x08, 0x2f, 0x0a, 0x57, 0xe9, 0x1c, 0x23, 0x17, 0x7b, 0x30, 0xc4, 0x14, 0x21, 0x79,
	0x2e, 0x96, 0xd0, 0xe2, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x6e, 0x88, 0x0a,
	0x3d, 0x90, 0x50, 0x10, 0x58, 0x42, 0xc8, 0x81, 0x8b, 0xdf, 0x11, 0xa2, 0x3b, 0x38, 0xb5, 0xa4,
	0x24, 0x33, 0x2f, 0xbd, 0x58, 0x82, 0x09, 0xac, 0x56, 0x0c, 0xaa, 0x16, 0x4d, 0x36, 0x08, 0x5d,
	0xb9, 0x90, 0x01, 0x17, 0x57, 0x70, 0x1e, 0x54, 0xb0, 0x58, 0x82, 0x59, 0x81, 0x59, 0x83, 0xdb,
	0x48, 0x00, 0xaa, 0x19, 0x2e, 0x11, 0x84, 0xa4, 0x46, 0x48, 0x8f, 0x8b, 0xd3, 0xab, 0xbc, 0xc4,
	0x39, 0x27, 0x31, 0x33, 0xb7, 0x58, 0x82, 0x05, 0x6c, 0x1b, 0x4c, 0x03, 0x5c, 0x3c, 0x08, 0xa1,
	0xc4, 0x89, 0x33, 0x8a, 0x5d, 0xcf, 0x1a, 0x2c, 0x9f, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x0d, 0x05, 0xea, 0xb3, 0x27, 0x01, 0x00, 0x00,
}
