// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sn_account.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SNAccount struct {
	ID                   uint64               `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TypeID               uint64               `protobuf:"varint,2,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	SNID                 string               `protobuf:"bytes,3,opt,name=SNID,proto3" json:"SNID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SNAccount) Reset()         { *m = SNAccount{} }
func (m *SNAccount) String() string { return proto.CompactTextString(m) }
func (*SNAccount) ProtoMessage()    {}
func (*SNAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_814abc1b2d999325, []int{0}
}

func (m *SNAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SNAccount.Unmarshal(m, b)
}
func (m *SNAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SNAccount.Marshal(b, m, deterministic)
}
func (m *SNAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SNAccount.Merge(m, src)
}
func (m *SNAccount) XXX_Size() int {
	return xxx_messageInfo_SNAccount.Size(m)
}
func (m *SNAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SNAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SNAccount proto.InternalMessageInfo

func (m *SNAccount) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SNAccount) GetTypeID() uint64 {
	if m != nil {
		return m.TypeID
	}
	return 0
}

func (m *SNAccount) GetSNID() string {
	if m != nil {
		return m.SNID
	}
	return ""
}

func (m *SNAccount) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*SNAccount)(nil), "proto.SNAccount")
}

func init() {
	proto.RegisterFile("sn_account.proto", fileDescriptor_814abc1b2d999325)
}

var fileDescriptor_814abc1b2d999325 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0xce, 0x8b, 0x4f,
	0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53,
	0x52, 0xf2, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x5e, 0x52, 0x69, 0x9a, 0x7e, 0x49,
	0x66, 0x6e, 0x6a, 0x71, 0x49, 0x62, 0x6e, 0x01, 0x44, 0x9d, 0x52, 0x23, 0x23, 0x17, 0x67, 0xb0,
	0x9f, 0x23, 0x44, 0xaf, 0x10, 0x1f, 0x17, 0x93, 0xa7, 0x8b, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4b,
	0x10, 0x93, 0xa7, 0x8b, 0x90, 0x18, 0x17, 0x5b, 0x48, 0x65, 0x41, 0xaa, 0xa7, 0x8b, 0x04, 0x13,
	0x58, 0x0c, 0xca, 0x13, 0x12, 0xe2, 0x62, 0x09, 0xf6, 0xf3, 0x74, 0x91, 0x60, 0x56, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x2c, 0xb8, 0x38, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x53, 0x1c,
	0x4b, 0x24, 0x58, 0x14, 0x18, 0x35, 0xb8, 0x8d, 0xa4, 0xf4, 0x20, 0xd6, 0xeb, 0xc1, 0xac, 0xd7,
	0x0b, 0x81, 0x59, 0x1f, 0x84, 0x50, 0xec, 0xc4, 0x19, 0xc5, 0xae, 0x67, 0x0d, 0x51, 0xc2, 0x06,
	0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x25, 0xe8, 0x70, 0xd1, 0x00, 0x00, 0x00,
}
