// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Token struct {
	AccessToken          string               `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	TokenType            string               `protobuf:"bytes,2,opt,name=TokenType,proto3" json:"TokenType,omitempty"`
	RefreshToken         string               `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	Expiry               *timestamp.Timestamp `protobuf:"bytes,4,opt,name=Expiry,proto3" json:"Expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *Token) GetExpiry() *timestamp.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func init() {
	proto.RegisterType((*Token)(nil), "proto.Token")
}

func init() {
	proto.RegisterFile("token.proto", fileDescriptor_3aff0bcd502840ab)
}

var fileDescriptor_3aff0bcd502840ab = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0xcf, 0x4e,
	0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0xf2, 0xe9, 0xf9, 0xf9,
	0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x5e, 0x52, 0x69, 0x9a, 0x7e, 0x49, 0x66, 0x6e, 0x6a, 0x71, 0x49,
	0x62, 0x6e, 0x01, 0x44, 0x9d, 0xd2, 0x7c, 0x46, 0x2e, 0xd6, 0x10, 0x90, 0x3e, 0x21, 0x05, 0x2e,
	0x6e, 0xc7, 0xe4, 0xe4, 0xd4, 0xe2, 0x62, 0x30, 0x57, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08,
	0x59, 0x48, 0x48, 0x86, 0x8b, 0x13, 0xcc, 0x08, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x02, 0xcb, 0x23,
	0x04, 0x84, 0x94, 0xb8, 0x78, 0x82, 0x52, 0xd3, 0x8a, 0x52, 0x8b, 0x33, 0x20, 0x06, 0x30, 0x83,
	0x15, 0xa0, 0x88, 0x09, 0x19, 0x71, 0xb1, 0xb9, 0x56, 0x14, 0x64, 0x16, 0x55, 0x4a, 0xb0, 0x28,
	0x30, 0x6a, 0x70, 0x1b, 0x49, 0xe9, 0x41, 0xdc, 0xa7, 0x07, 0x73, 0x9f, 0x5e, 0x08, 0xcc, 0x7d,
	0x41, 0x50, 0x95, 0x4e, 0x9c, 0x51, 0xec, 0x7a, 0xd6, 0x10, 0x79, 0x36, 0x30, 0x65, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x1f, 0x84, 0xbe, 0x1d, 0xea, 0x00, 0x00, 0x00,
}
