version: '3.7'

services:

  db_reference:
    container_name: db_reference
    image: postgres:13-alpine
    volumes:
        - postgresql-reference:/var/lib/postgresql/data
        - ./data/db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB:        reference
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  1gjcnuhtc1!
#    command: postgres -c listen_addresses='*'
    ports:
      - 5000:5432
    networks:
      - backend
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_data1:
    container_name: db_data1
    image: postgres:13-alpine
    volumes:
      - postgresql-data1:/var/lib/postgresql/data
      - ./data/db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB:        data
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  1gjcnuhtc1!
#    command: postgres -c listen_addresses='*'
    ports:
      - 5001:5432
    networks:
      - backend
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_data2:
    container_name: db_data2
    image: postgres:13-alpine
    volumes:
      - postgresql-data2:/var/lib/postgresql/data
      - ./data/db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB:        data
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  1gjcnuhtc1!
    ports:
      - 5002:5432
    networks:
      - backend
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_data3:
    container_name: db_data3
    image: postgres:13-alpine
    volumes:
      - postgresql-data3:/var/lib/postgresql/data
      - ./data/db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB:        data
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  1gjcnuhtc1!
    ports:
      - 5003:5432
    networks:
      - backend
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_data_p1:
    container_name: db_data_p1
    image: postgres:13-alpine
    volumes:
      - postgresql-data_p1:/var/lib/postgresql/data
      - ./data/db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB:        data
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  1gjcnuhtc1!
    ports:
      - 5101:5432
    networks:
      - backend
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_data_p2:
    container_name: db_data_p2
    image: postgres:13-alpine
    volumes:
      - postgresql-data_p2:/var/lib/postgresql/data
      - ./data/db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB:        data
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  1gjcnuhtc1!
    ports:
      - 5102:5432
    networks:
      - backend
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_data_p3:
    container_name: db_data_p3
    image: postgres:13-alpine
    volumes:
      - postgresql-data_p3:/var/lib/postgresql/data
      - ./data/db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB:        data
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  1gjcnuhtc1!
    ports:
      - 5103:5432
    networks:
      - backend
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    container_name: redis
    image: redis:6.0
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
        - backend
    tty: true

volumes:
  postgresql-reference:
    driver: local
  postgresql-data1:
    driver: local
  postgresql-data2:
    driver: local
  postgresql-data3:
    driver: local
  postgresql-data_p1:
    driver: local
  postgresql-data_p2:
    driver: local
  postgresql-data_p3:
    driver: local
networks:
  backend:
