server:
  httplisten:  "0.0.0.0:80"

log:
  encoding:       "json"
  outputpaths:
    - "log/app.log"
    - "stdout"
  level:          "debug"
  initialfields:
    app:          "app"

db:
  reference:
    dialect:        "postgres"
    dsn:            "host=db_reference port=5432 dbname=reference user=postgres password=1gjcnuhtc1! sslmode=disable"
    isautomigrate:  True
    log:
      loglevel:     4
  datasharding:
    default:
      capacity:  10
      items:
        - dialect:        "postgres"
          dsn:            "host=db_data1 port=5432 dbname=data user=postgres password=1gjcnuhtc1! sslmode=disable"
          isautomigrate:  True
          log:
            loglevel:     4
        - dialect:        "postgres"
          dsn:            "host=db_data2 port=5432 dbname=data user=postgres password=1gjcnuhtc1! sslmode=disable"
          isautomigrate:  True
          log:
            loglevel:     4
        - dialect:        "postgres"
          dsn:            "host=db_data3 port=5432 dbname=data user=postgres password=1gjcnuhtc1! sslmode=disable"
          isautomigrate:  True
          log:
            loglevel:     4

    bytypes:
      post:
        capacity:  20
        items:
          - dialect:        "postgres"
            dsn:            "host=db_data_p1 port=5432 dbname=data user=postgres password=1gjcnuhtc1! sslmode=disable"
            isautomigrate:  True
            log:
              loglevel:     4
          - dialect:        "postgres"
            dsn:            "host=db_data_p2 port=5432 dbname=data user=postgres password=1gjcnuhtc1! sslmode=disable"
            isautomigrate:  True
            log:
              loglevel:     4
          - dialect:        "postgres"
            dsn:            "host=db_data_p3 port=5432 dbname=data user=postgres password=1gjcnuhtc1! sslmode=disable"
            isautomigrate:  True
            log:
              loglevel:     4

  redis:
    addrs:
      - "redis:6379"
    login:    ""
    password: ""
    dbname:   0


jwtsigningkey: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
jwtexpiration: 72
sessionlifetime: 96
