isautomigrate:  true
languages:
  eng: "english"
  rus: "русский"

propertyunits:
  item:
    eng:
      name: "item"
      description: "item"
    rus:
      name: "шт."
      description: "штук"
  mm:
    eng:
      name: "mm"
      description: "millimeters"
    rus:
      name: "мм"
      description: "миллиметры"

entitytypes:
  user:
    texts:
      eng:
        name: "user"
        description: "user"
      rus:
        name: "пользователь"
        description: "пользователь"
    properties:
      name:
        propertytype: "text"
        texts:
          eng:
            name: "name"
            description: "name"
          rus:
            name: "имя"
            description: "имя"
