isautomigrate:  true
languages:
   - code: "eng"
     name: "english"
     cfgname: "english"
   - code: "rus"
     name: "русский"
     cfgname: "russian"

propertyunits:
  - sysname: "item"
    texts:
      eng:
        name: "item"
        description: "item"
      rus:
        name: "шт."
        description: "штук"
  - sysname: "mm"
    texts:
      eng:
        name: "mm"
        description: "millimeters"
      rus:
        name: "мм"
        description: "миллиметры"
  - sysname: "year"
    texts:
      eng:
        name: "year"
        description: "year"
      rus:
        name: "лет"
        description: "лет"
  - sysname: "kg"
    texts:
      eng:
        name: "kg"
        description: "kilogram"
      rus:
        name: "кг"
        description: "килограмм"

entitytypes:
  - sysname: "User"
    texts:
      eng:
        name: "user"
      rus:
        name: "пользователь"
    properties:
      - sysname: "User.Email"
        propertytype: "utext"
        texts:
          eng:
            name: "email"
          rus:
            name: "email"
      - sysname: "User.AccountID"
        propertytype: "utext"
        texts:
          eng:
            name: "account ID"
          rus:
            name: "ID аккаунта"
  - sysname: "SNAccount"
    texts:
      eng:
        name: "social net account"
      rus:
        name: "аккаунт в социальной сети"
    properties:
      - sysname: "SNAccount.SNID"
        propertytype: "utext"
        texts:
          eng:
            name: "social net account ID"
          rus:
            name: "идентификатор аккаунта в социальной сети"
  - sysname: "Advertiser"
    texts:
      eng:
        name: "advertiser"
      rus:
        name: "рекламодатель"
    properties:
      - sysname: "Advertiser.Name"
        propertytype: "text"
        texts:
          eng:
            name: "name"
          rus:
            name: "имя"
  - sysname: "AdvertisingCampaign"
    texts:
      eng:
        name: "advertising campaign"
      rus:
        name: "рекламная кампания"
    properties:
      - sysname: "AdvertisingCampaign.Name"
        propertytype: "text"
        texts:
          eng:
            name: "name"
          rus:
            name: "имя"
  - sysname: "Offer"
    texts:
      eng:
        name: "offer"
      rus:
        name: "предложение"
    properties:
      - sysname: "Offer.CreatedAt"
        propertytype: "time"
        texts:
          eng:
            name: "date of creation"
          rus:
            name: "дата создания"
      - sysname: "Offer.StartedAt"
        propertytype: "time"
        texts:
          eng:
            name: "date of start"
          rus:
            name: "дата начала"
      - sysname: "Offer.FinishedAt"
        propertytype: "time"
        texts:
          eng:
            name: "date of finish"
          rus:
            name: "дата завершения"

relations:
  - sysname: "User.SNAccount"
    texts:
      eng:
        name: "social nets accounts"
      rus:
        name: "аккаунты в социальных сетях"
    UndependedEntityType: "SNAccount"
    DependedEntityType: "User"
  - sysname: "Advertiser.AdvertisingCampaigns"
    texts:
      eng:
        name: "advertising campaigns"
      rus:
        name: "рекламные кампании"
    UndependedEntityType: "AdvertisingCampaign"
    DependedEntityType: "Advertiser"
  - sysname: "AdvertisingCampaign.Offers"
    texts:
      eng:
        name: "offers"
      rus:
        name: "предложения"
    UndependedEntityType: "Offer"
    DependedEntityType: "AdvertisingCampaign"
