isautomigrate:  true
languages:
   - code: "eng"
     name: "english"
     cfgname: "english"
   - code: "rus"
     name: "русский"
     cfgname: "russian"

propertyunits:
  item:
    eng:
      name: "item"
      description: "item"
    rus:
      name: "шт."
      description: "штук"
  mm:
    eng:
      name: "mm"
      description: "millimeters"
    rus:
      name: "мм"
      description: "миллиметры"
  year:
    eng:
      name: "year"
      description: "years"
    rus:
      name: "лет"
      description: "лет"
  kg:
    eng:
      name: "kg"
      description: "kilogram"
    rus:
      name: "кг"
      description: "килограмм"

entitytypes:
  User:
    texts:
      eng:
        name: "user"
        description: "user"
      rus:
        name: "пользователь"
        description: "пользователь"
    properties:
      Email:
        propertytype: "text"
        texts:
          eng:
            name: "email"
          rus:
            name: "email"
      Phone:
        propertytype: "int"
        texts:
          eng:
            name: "phone"
          rus:
            name: "телефон"
  Advertiser:
    Name:
      propertytype: "text"
      texts:
        eng:
          name: "name"
        rus:
          name: "имя"
  AdvertisingCampaign:
    Name:
      propertytype: "text"
      texts:
        eng:
          name: "name"
        rus:
          name: "имя"
  Offer:
    CreatedAt:
      propertytype: "time"
      texts:
        eng:
          name: "date of creation"
        rus:
          name: "дата создания"
    StartedAt:
      propertytype: "time"
      texts:
        eng:
          name: "date of start"
        rus:
          name: "дата начала"
    FinishedAt:
      propertytype: "time"
      texts:
        eng:
          name: "date of finish"
        rus:
          name: "дата завершения"
