isautomigrate:  true
languages:
   - code: "eng"
     name: "english"
     cfgname: "english"
   - code: "rus"
     name: "русский"
     cfgname: "russian"

propertyunits:
  item:
    eng:
      name: "item"
      description: "item"
    rus:
      name: "шт."
      description: "штук"
  mm:
    eng:
      name: "mm"
      description: "millimeters"
    rus:
      name: "мм"
      description: "миллиметры"
  year:
    eng:
      name: "year"
      description: "years"
    rus:
      name: "лет"
      description: "лет"
  kg:
    eng:
      name: "kg"
      description: "kilogram"
    rus:
      name: "кг"
      description: "килограмм"

entitytypes:
  user:
    texts:
      eng:
        name: "user"
        description: "user"
      rus:
        name: "пользователь"
        description: "пользователь"
    properties:
      name:
        propertytype: "text"
        texts:
          eng:
            name: "name"
            description: "name"
          rus:
            name: "имя"
            description: "имя"
      age:
        propertytype: "int"
        propertyunit: "year"
        texts:
          eng:
            name: "age"
            description: "age"
          rus:
            name: "возраст"
            description: "возраст"
      height:
        propertytype: "float"
        propertyunit: "mm"
        texts:
          eng:
            name: "height"
            description: "height"
          rus:
            name: "рост"
            description: "рост"
      weight:
        propertytype: "float"
        propertyunit: "kg"
        texts:
          eng:
            name: "weight"
            description: "weight"
          rus:
            name: "масса"
            description: "масса"
