// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tg_account/tg_account.proto

package tg_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TgAccount struct {
	ID                   uint64               `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TgID                 string               `protobuf:"bytes,2,opt,name=TgID,proto3" json:"TgID,omitempty"`
	AuthSession          *AuthSession         `protobuf:"bytes,3,opt,name=AuthSession,proto3" json:"AuthSession,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TgAccount) Reset()         { *m = TgAccount{} }
func (m *TgAccount) String() string { return proto.CompactTextString(m) }
func (*TgAccount) ProtoMessage()    {}
func (*TgAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b2ac9b320d8f54d, []int{0}
}

func (m *TgAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgAccount.Unmarshal(m, b)
}
func (m *TgAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgAccount.Marshal(b, m, deterministic)
}
func (m *TgAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgAccount.Merge(m, src)
}
func (m *TgAccount) XXX_Size() int {
	return xxx_messageInfo_TgAccount.Size(m)
}
func (m *TgAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_TgAccount.DiscardUnknown(m)
}

var xxx_messageInfo_TgAccount proto.InternalMessageInfo

func (m *TgAccount) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TgAccount) GetTgID() string {
	if m != nil {
		return m.TgID
	}
	return ""
}

func (m *TgAccount) GetAuthSession() *AuthSession {
	if m != nil {
		return m.AuthSession
	}
	return nil
}

func (m *TgAccount) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type AuthSession struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Salt                 int64    `protobuf:"varint,3,opt,name=Salt,proto3" json:"Salt,omitempty"`
	Hostname             string   `protobuf:"bytes,4,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSession) Reset()         { *m = AuthSession{} }
func (m *AuthSession) String() string { return proto.CompactTextString(m) }
func (*AuthSession) ProtoMessage()    {}
func (*AuthSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b2ac9b320d8f54d, []int{1}
}

func (m *AuthSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSession.Unmarshal(m, b)
}
func (m *AuthSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSession.Marshal(b, m, deterministic)
}
func (m *AuthSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSession.Merge(m, src)
}
func (m *AuthSession) XXX_Size() int {
	return xxx_messageInfo_AuthSession.Size(m)
}
func (m *AuthSession) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSession.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSession proto.InternalMessageInfo

func (m *AuthSession) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AuthSession) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *AuthSession) GetSalt() int64 {
	if m != nil {
		return m.Salt
	}
	return 0
}

func (m *AuthSession) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func init() {
	proto.RegisterType((*TgAccount)(nil), "tg_account.TgAccount")
	proto.RegisterType((*AuthSession)(nil), "tg_account.AuthSession")
}

func init() {
	proto.RegisterFile("tg_account/tg_account.proto", fileDescriptor_8b2ac9b320d8f54d)
}

var fileDescriptor_8b2ac9b320d8f54d = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3d, 0x4f, 0x84, 0x40,
	0x10, 0x86, 0xc3, 0x47, 0x8c, 0xec, 0x5d, 0x8c, 0xd9, 0x46, 0x82, 0x85, 0xe4, 0x2a, 0xaa, 0xdd,
	0xe4, 0xb4, 0xd0, 0x12, 0xa5, 0x38, 0x62, 0xb7, 0x47, 0x65, 0x63, 0x16, 0x5c, 0x17, 0x12, 0x60,
	0x09, 0x0c, 0xc5, 0xf9, 0x7b, 0xfc, 0xa1, 0x86, 0x21, 0x27, 0x5c, 0xf7, 0xcc, 0x3b, 0xef, 0x66,
	0x9f, 0x0c, 0xb9, 0x07, 0xfd, 0x29, 0x8b, 0xc2, 0x8c, 0x2d, 0xf0, 0x05, 0x59, 0xd7, 0x1b, 0x30,
	0x94, 0x2c, 0x49, 0xf0, 0xa0, 0x8d, 0xd1, 0xb5, 0xe2, 0xb8, 0xc9, 0xc7, 0x6f, 0x0e, 0x55, 0xa3,
	0x06, 0x90, 0x4d, 0x37, 0x97, 0x77, 0xbf, 0x16, 0xf1, 0x32, 0x1d, 0xcf, 0x75, 0x7a, 0x43, 0xec,
	0x34, 0xf1, 0xad, 0xd0, 0x8a, 0x5c, 0x61, 0xa7, 0x09, 0xa5, 0xc4, 0xcd, 0x74, 0x9a, 0xf8, 0x76,
	0x68, 0x45, 0x9e, 0x40, 0xa6, 0x2f, 0x64, 0x13, 0x8f, 0x50, 0x1e, 0xd5, 0x30, 0x54, 0xa6, 0xf5,
	0x9d, 0xd0, 0x8a, 0x36, 0xfb, 0x3b, 0xb6, 0xd2, 0x58, 0xad, 0xc5, 0xba, 0x4b, 0x9f, 0x89, 0xf7,
	0xd6, 0x2b, 0x09, 0xea, 0x2b, 0x06, 0xdf, 0xc5, 0x87, 0x01, 0x9b, 0x0d, 0xd9, 0xd9, 0x90, 0x65,
	0x67, 0x43, 0xb1, 0x94, 0x77, 0xc5, 0xc5, 0xa7, 0xf4, 0x96, 0x38, 0xef, 0xea, 0x84, 0xa2, 0x5b,
	0x31, 0xe1, 0x64, 0x7a, 0x90, 0x43, 0x89, 0xa6, 0x5b, 0x81, 0x3c, 0x65, 0x47, 0x59, 0x03, 0x2a,
	0x3a, 0x02, 0x99, 0x06, 0xe4, 0xfa, 0x60, 0x06, 0x68, 0x65, 0xa3, 0xd0, 0xc0, 0x13, 0xff, 0xf3,
	0xeb, 0xd3, 0xc7, 0x5e, 0x57, 0x50, 0x8e, 0x39, 0x2b, 0x4c, 0xc3, 0x4f, 0xb2, 0x1f, 0x7f, 0xb8,
	0xec, 0x3a, 0x5e, 0xb5, 0xa0, 0xfa, 0x56, 0xd6, 0x38, 0xa0, 0xe7, 0xea, 0xe8, 0xf9, 0x15, 0x26,
	0x8f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x96, 0x37, 0x29, 0x53, 0x94, 0x01, 0x00, 0x00,
}
