// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwt/jwt.proto

package jwt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	user "github.com/yaruz/app/internal/app/proto/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Claims struct {
	RegisteredClaims     *RegisteredClaims `protobuf:"bytes,1,opt,name=RegisteredClaims,proto3" json:"RegisteredClaims,omitempty"`
	TokenData            *TokenData        `protobuf:"bytes,2,opt,name=TokenData,proto3" json:"TokenData,omitempty"`
	AccessToken          string            `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Claims) Reset()         { *m = Claims{} }
func (m *Claims) String() string { return proto.CompactTextString(m) }
func (*Claims) ProtoMessage()    {}
func (*Claims) Descriptor() ([]byte, []int) {
	return fileDescriptor_435ffb6baf1c81ca, []int{0}
}

func (m *Claims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claims.Unmarshal(m, b)
}
func (m *Claims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claims.Marshal(b, m, deterministic)
}
func (m *Claims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claims.Merge(m, src)
}
func (m *Claims) XXX_Size() int {
	return xxx_messageInfo_Claims.Size(m)
}
func (m *Claims) XXX_DiscardUnknown() {
	xxx_messageInfo_Claims.DiscardUnknown(m)
}

var xxx_messageInfo_Claims proto.InternalMessageInfo

func (m *Claims) GetRegisteredClaims() *RegisteredClaims {
	if m != nil {
		return m.RegisteredClaims
	}
	return nil
}

func (m *Claims) GetTokenData() *TokenData {
	if m != nil {
		return m.TokenData
	}
	return nil
}

func (m *Claims) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type RegisteredClaims struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Issuer               string               `protobuf:"bytes,2,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	Subject              string               `protobuf:"bytes,3,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Audience             []string             `protobuf:"bytes,4,rep,name=Audience,proto3" json:"Audience,omitempty"`
	ExpiresAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=ExpiresAt,proto3" json:"ExpiresAt,omitempty"`
	NotBefore            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=NotBefore,proto3" json:"NotBefore,omitempty"`
	IssuedAt             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=IssuedAt,proto3" json:"IssuedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegisteredClaims) Reset()         { *m = RegisteredClaims{} }
func (m *RegisteredClaims) String() string { return proto.CompactTextString(m) }
func (*RegisteredClaims) ProtoMessage()    {}
func (*RegisteredClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_435ffb6baf1c81ca, []int{1}
}

func (m *RegisteredClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredClaims.Unmarshal(m, b)
}
func (m *RegisteredClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredClaims.Marshal(b, m, deterministic)
}
func (m *RegisteredClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredClaims.Merge(m, src)
}
func (m *RegisteredClaims) XXX_Size() int {
	return xxx_messageInfo_RegisteredClaims.Size(m)
}
func (m *RegisteredClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredClaims.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredClaims proto.InternalMessageInfo

func (m *RegisteredClaims) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RegisteredClaims) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *RegisteredClaims) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *RegisteredClaims) GetAudience() []string {
	if m != nil {
		return m.Audience
	}
	return nil
}

func (m *RegisteredClaims) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *RegisteredClaims) GetNotBefore() *timestamp.Timestamp {
	if m != nil {
		return m.NotBefore
	}
	return nil
}

func (m *RegisteredClaims) GetIssuedAt() *timestamp.Timestamp {
	if m != nil {
		return m.IssuedAt
	}
	return nil
}

type TokenData struct {
	SessionID            string     `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	User                 *user.User `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TokenData) Reset()         { *m = TokenData{} }
func (m *TokenData) String() string { return proto.CompactTextString(m) }
func (*TokenData) ProtoMessage()    {}
func (*TokenData) Descriptor() ([]byte, []int) {
	return fileDescriptor_435ffb6baf1c81ca, []int{2}
}

func (m *TokenData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenData.Unmarshal(m, b)
}
func (m *TokenData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenData.Marshal(b, m, deterministic)
}
func (m *TokenData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenData.Merge(m, src)
}
func (m *TokenData) XXX_Size() int {
	return xxx_messageInfo_TokenData.Size(m)
}
func (m *TokenData) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenData.DiscardUnknown(m)
}

var xxx_messageInfo_TokenData proto.InternalMessageInfo

func (m *TokenData) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *TokenData) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Claims)(nil), "jwt.Claims")
	proto.RegisterType((*RegisteredClaims)(nil), "jwt.RegisteredClaims")
	proto.RegisterType((*TokenData)(nil), "jwt.TokenData")
}

func init() {
	proto.RegisterFile("jwt/jwt.proto", fileDescriptor_435ffb6baf1c81ca)
}

var fileDescriptor_435ffb6baf1c81ca = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4f, 0xa3, 0x40,
	0x18, 0xc5, 0x03, 0xed, 0xd2, 0x32, 0xcd, 0x76, 0x37, 0x93, 0xec, 0x66, 0x42, 0x8c, 0x92, 0x9e,
	0x9a, 0xa8, 0x90, 0xd4, 0xc4, 0x78, 0xa5, 0xd6, 0x03, 0x17, 0x0f, 0xd3, 0x7a, 0xf1, 0x06, 0xf4,
	0x2b, 0x0e, 0x16, 0x86, 0xcc, 0x0c, 0xa9, 0xfa, 0xaf, 0xe8, 0x1f, 0x6b, 0x18, 0x5a, 0xda, 0xd8,
	0x43, 0x2f, 0x84, 0xef, 0xc7, 0x7b, 0xcc, 0x9b, 0x97, 0x0f, 0xfd, 0xce, 0x36, 0xca, 0xcf, 0x36,
	0xca, 0x2b, 0x05, 0x57, 0x1c, 0x77, 0xb2, 0x8d, 0x72, 0x2e, 0x52, 0xce, 0xd3, 0x35, 0xf8, 0x1a,
	0xc5, 0xd5, 0xca, 0x57, 0x2c, 0x07, 0xa9, 0xa2, 0xbc, 0x6c, 0x54, 0xce, 0x9f, 0x4a, 0x82, 0xf0,
	0xeb, 0x47, 0x03, 0x46, 0x9f, 0x06, 0xb2, 0xee, 0xd7, 0x11, 0xcb, 0x25, 0x0e, 0xd0, 0x5f, 0x0a,
	0x29, 0x93, 0x0a, 0x04, 0x2c, 0x1b, 0x46, 0x0c, 0xd7, 0x18, 0x0f, 0x26, 0xff, 0xbc, 0xfa, 0x9c,
	0x9f, 0x1f, 0xe9, 0x91, 0x1c, 0x5f, 0x21, 0x7b, 0xc1, 0x5f, 0xa1, 0x98, 0x45, 0x2a, 0x22, 0xa6,
	0xf6, 0x0e, 0xb5, 0xb7, 0xa5, 0x74, 0x2f, 0xc0, 0x2e, 0x1a, 0x04, 0x49, 0x02, 0x52, 0x6a, 0x44,
	0x3a, 0xae, 0x31, 0xb6, 0xe9, 0x21, 0x1a, 0x7d, 0x99, 0xc7, 0x99, 0xf0, 0x10, 0x99, 0xe1, 0x4c,
	0x27, 0xb3, 0xa9, 0x19, 0xce, 0xf0, 0x7f, 0x64, 0x85, 0x52, 0x56, 0x20, 0xf4, 0x89, 0x36, 0xdd,
	0x4e, 0x98, 0xa0, 0xde, 0xbc, 0x8a, 0x33, 0x48, 0xd4, 0xf6, 0xd7, 0xbb, 0x11, 0x3b, 0xa8, 0x1f,
	0x54, 0x4b, 0x06, 0x45, 0x02, 0xa4, 0xeb, 0x76, 0xc6, 0x36, 0x6d, 0x67, 0x7c, 0x87, 0xec, 0x87,
	0xb7, 0x92, 0x09, 0x90, 0x81, 0x22, 0xbf, 0xf4, 0x15, 0x1c, 0xaf, 0xa9, 0xd5, 0xdb, 0xd5, 0xea,
	0x2d, 0x76, 0xb5, 0xd2, 0xbd, 0xb8, 0x76, 0x3e, 0x72, 0x35, 0x85, 0x15, 0x17, 0x40, 0xac, 0xd3,
	0xce, 0x56, 0x8c, 0x6f, 0x51, 0x5f, 0x67, 0x5e, 0x06, 0x8a, 0xf4, 0x4e, 0x1a, 0x5b, 0xed, 0x28,
	0x3c, 0xa8, 0x1b, 0x9f, 0x21, 0x7b, 0x0e, 0x52, 0x32, 0x5e, 0xb4, 0xed, 0xec, 0x01, 0x3e, 0x47,
	0xdd, 0x27, 0xb9, 0xad, 0x68, 0x30, 0x41, 0x9e, 0x5e, 0x81, 0x9a, 0x50, 0xcd, 0xa7, 0xd7, 0xcf,
	0x97, 0x29, 0x53, 0x2f, 0x55, 0xec, 0x25, 0x3c, 0xf7, 0xdf, 0x23, 0x51, 0x7d, 0xf8, 0x51, 0x59,
	0xfa, 0xac, 0x50, 0x20, 0x8a, 0x68, 0xad, 0x07, 0x1d, 0xa6, 0xde, 0xb9, 0xd8, 0xd2, 0xaf, 0x37,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x0c, 0x6f, 0x74, 0x85, 0x02, 0x00, 0x00,
}
